# Proyecto 3 - MLOps: compose unificado
#
# Levantar todo:
#   docker compose up -d --build
#
# Variables recomendadas en .env: AIRFLOW_UID, AIRFLOW_PROJ_DIR=../Airflow

include:
  - compose/minio.yml
  - compose/postgres.yml
  - compose/postgres-dataset.yml
  # - compose/redis.yml
  # - compose/airflow.yml
  - compose/airflow-slim.yml
  - compose/adminer.yml
  - compose/mlflow.yml
  - compose/api_source.yml
  - compose/api.yml
  - compose/prometheus.yml
  - compose/grafana.yml
  - compose/streamlit.yml
  - compose/locust.yml
