apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-dataset-db-volume
  namespace: mlops-infra
  labels:
    app: postgres-dataset
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
