
services:
  mlflow:
    build:
      context: ../mlflow
      dockerfile: Dockerfile
    container_name: MLflow
    depends_on:
      mlflow-db:
        condition: service_healthy
      minio:
        condition: service_started
      minio-init:
        condition: service_completed_successfully
    ports:
      - "5001:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_DB_HOST: mlflow-db
      MLFLOW_DB_PORT: "5432"
      MLFLOW_DB_NAME: mlflow
      MLFLOW_DB_USER: mlflow
      MLFLOW_DB_PASSWORD: mlflow
    restart: always

  mlflow-db:
    image: postgres:13
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5434:5432"
    volumes:
      - mlflow-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mlflow", "-d", "mlflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

volumes:
  mlflow-db-volume: