# Configuracion minima para ambiente local de laboratorio.
executor: LocalExecutor

# Imagen personalizada con dependencias comunes para el proyecto.
airflowVersion: "2.11.1"

images:
  airflow:
    repository: airflow-local-dags
    tag: 0.0.1

# # Configuración scheduler
# config:
#   scheduler:
#     parsing_processes: 1
#     min_file_process_interval: 120

env:
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "False"

  # Variables de conexión a la base de datos del dataset.
  - name: POSTGRES_DATASET_HOST
    value: postgres-dataset
  - name: POSTGRES_DATASET_PORT
    value: "5432"
  - name: POSTGRES_DATASET_USER
    value: airflow
  - name: POSTGRES_DATASET_PASSWORD
    value: airflow
  - name: POSTGRES_DATASET_DATABASE
    value: diabetic_data 

  # Variables de conexión a MinIO (S3).
  - name: AWS_ACCESS_KEY_ID
    value: minioadmin
  - name: AWS_SECRET_ACCESS_KEY
    value: minioadmin
  - name: AWS_DEFAULT_REGION
    value: us-east-1
  - name: MINIO_ENDPOINT
    value: http://minio:9000

  # Variables de conexión a MLflow.
  - name: MLFLOW_S3_ENDPOINT_URL
    value: http://minio:9000
  - name: MLFLOW_TRACKING_URI
    value: http://mlflow:5000

  # Variable de conexión a API de inferencia.
  - name: INFERENCE_API_URL
    value: "http://api:8000"

# Mantener componentes minimos para pruebas locales.
workers:
  replicas: 1

triggerer:
  enabled: true

postgresql:
  enabled: true

redis:
  enabled: false