# API de datos (Covertype) para pruebas locales.
# Sirve datos por batches; el DAG de Airflow se conecta a este servicio como api-data.

services:
  api-source:
    image: cristiandiaz13/mlops-puj:data-api-pf-v1
    container_name: SourceAPI
    ports:
      - "8001:80"
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.25"
    restart: always
