services:
  locust:
    build:
      context: ../locust
      dockerfile: Dockerfile
    container_name: Locust
    ports:
      - "8089:8089"
    depends_on:
      - api
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.25"
    restart: unless-stopped
