services:
  prometheus:
    build:
      context: ../prometheus
      dockerfile: Dockerfile
    container_name: Prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.25"
    restart: unless-stopped

volumes:
  prometheus-data:
