apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-db-volume
  namespace: mlops-infra
  labels:
    app: mlflow-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
