apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: mlops-infra
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin"
  MLFLOW_DB_USER: "mlflow"
  MLFLOW_DB_PASSWORD: "mlflow"
