apiVersion: v1
kind: Service
metadata:
  name: mlflow-db
  namespace: mlops-infra
  labels:
    app: mlflow-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: mlflow-db
