apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Users\sebas\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f compose/minio.yml -o komposefiles/minio/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: minio-init
  name: minio-init
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for MinIO...";

          until mc alias set local http://minio:9000 minioadmin minioadmin; do
            echo "MinIO not ready yet...";
            sleep 2;
          done;

          echo "MinIO ready";

          mc mb -p local/mlflows3;
          mc anonymous set none local/mlflows3;
          mc mb -p local/diabetic-project;
      image: minio/mc:latest
      name: minio-init
  restartPolicy: Never
