services:
  taller_service:
    build: app
    ports:
      - "8001:8001"
    volumes:
      - './app:/app'
      - './models:/models'
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  jupyterlab:
    build: train
    ports:
      - "8888:8888"
    volumes:
      - ./train:/workspace
      - ./models:/models
    restart: unless-stopped
